// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Family struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FamilyMember struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type User struct {
	ID        uuid.UUID
	GoogleSub string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
