// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type AuthNonce struct {
	Nonce     string
	ExpiresAt time.Time
}

type Family struct {
	ID        uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FamilyMember struct {
	FamilyID uuid.UUID
	UserID   uuid.UUID
	Role     string
	JoinedAt time.Time
}

type Session struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  []byte
	CreatedAt  time.Time
	ExpiresAt  time.Time
	LastUsedAt time.Time
}

type User struct {
	ID        uuid.UUID
	GoogleSub string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
