// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nonces.sql

package db

import (
	"context"
	"time"
)

const consumeNonce = `-- name: ConsumeNonce :one
DELETE FROM auth_nonces
WHERE nonce = $1 AND expires_at > now()
RETURNING nonce
`

// Checks and consumes the nonce in one statement. Of two concurrent logins
// with the same nonce, only one gets the row back.
func (q *Queries) ConsumeNonce(ctx context.Context, nonce string) (string, error) {
	row := q.db.QueryRow(ctx, consumeNonce, nonce)
	var nonce_2 string
	err := row.Scan(&nonce_2)
	return nonce_2, err
}

const createNonce = `-- name: CreateNonce :exec
INSERT INTO auth_nonces (nonce, expires_at)
VALUES ($1, $2)
`

type CreateNonceParams struct {
	Nonce     string
	ExpiresAt time.Time
}

func (q *Queries) CreateNonce(ctx context.Context, arg CreateNonceParams) error {
	_, err := q.db.Exec(ctx, createNonce, arg.Nonce, arg.ExpiresAt)
	return err
}

const deleteExpiredNonces = `-- name: DeleteExpiredNonces :exec
DELETE FROM auth_nonces
WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredNonces(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredNonces)
	return err
}
